name: Auto Survey - 平日17時定期実行

on:
  schedule:
    # 平日17時（JST）= 平日8時（UTC）
    # 月〜金の8時UTC
    - cron: '0 8 * * 1-5'
  workflow_dispatch:  # 手動実行も可能

jobs:
  auto-survey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai
        pip install feedparser
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        pip install PyPDF2
        pip install python-dateutil

    - name: Run auto survey
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cd tools
        python main.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "Auto survey results - $(date '+%Y-%m-%d %H:%M:%S JST')"
          git push
        else
          echo "No changes to commit"
        fi